-- 029 : permissions par organisation (P1-06b)
-- 1. Normalise le mode du catalogue en 3 valeurs et l'impose par contrainte.
-- 2. Reglages propres a une organisation (appliques par l'Admin de SOCYTAY uniquement).
-- 3. Demandes de changement faites par les clients, a traiter par l'Admin de SOCYTAY.
-- Idempotent.

BEGIN;

UPDATE public.agent_permissions SET mode = 'AUTO' WHERE mode = 'Automatique';
UPDATE public.agent_permissions SET mode = 'APPROBATION_REQUISE' WHERE mode = 'Validation requise';

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'agent_permissions_mode_check' AND conrelid = 'public.agent_permissions'::regclass) THEN
    ALTER TABLE public.agent_permissions ADD CONSTRAINT agent_permissions_mode_check CHECK (mode IN ('AUTO', 'APPROBATION_REQUISE', 'BLOQUE'));
  END IF;
END $$;

-- Reglage d'une organisation pour une action d'agent. Sans ligne : le mode du catalogue s'applique.
CREATE TABLE IF NOT EXISTS public.org_agent_permissions (
  org_id text NOT NULL,
  permission_id integer NOT NULL,
  mode text NOT NULL,
  granted_by text NOT NULL,
  granted_at timestamptz NOT NULL DEFAULT now(),
  note text,
  CONSTRAINT org_agent_permissions_pkey PRIMARY KEY (org_id, permission_id),
  CONSTRAINT org_agent_permissions_mode_check CHECK (mode IN ('AUTO', 'APPROBATION_REQUISE', 'BLOQUE')),
  CONSTRAINT org_agent_permissions_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.tenants(org_id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT org_agent_permissions_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES public.agent_permissions(id) ON DELETE CASCADE
);

-- Demande de changement faite par un client ; decision par l'Admin de SOCYTAY.
CREATE TABLE IF NOT EXISTS public.org_permission_requests (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id text NOT NULL,
  permission_id integer NOT NULL,
  requested_mode text NOT NULL,
  reason text,
  requested_by text NOT NULL,
  requested_at timestamptz NOT NULL DEFAULT now(),
  status text NOT NULL DEFAULT 'en_attente',
  decided_by text,
  decided_at timestamptz,
  decision_note text,
  CONSTRAINT org_permission_requests_mode_check CHECK (requested_mode IN ('AUTO', 'APPROBATION_REQUISE', 'BLOQUE')),
  CONSTRAINT org_permission_requests_status_check CHECK (status IN ('en_attente', 'accepte', 'refuse')),
  CONSTRAINT org_permission_requests_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.tenants(org_id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT org_permission_requests_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES public.agent_permissions(id) ON DELETE CASCADE
);

-- Une seule demande en attente par organisation et par action.
CREATE UNIQUE INDEX IF NOT EXISTS org_permission_requests_pending_idx
  ON public.org_permission_requests (org_id, permission_id) WHERE status = 'en_attente';

COMMENT ON TABLE public.org_agent_permissions IS 'Reglages de mode par organisation, poses par l''Admin de SOCYTAY. Prioritaires sur le mode du catalogue.';
COMMENT ON TABLE public.org_permission_requests IS 'Demandes de changement de mode faites par les clients ; traitees par l''Admin de SOCYTAY.';

COMMIT;
