-- 003 · Studio de workflow v2 (canvas) : condition, détails, bannière de run
-- Idempotent : peut être rejoué sans erreur.
-- Prérequis : 001 et 002 exécutés (tables workflows, workflow_nodes, 3 lignes workflows).

ALTER TABLE workflow_nodes DROP CONSTRAINT IF EXISTS workflow_nodes_kind_check;
ALTER TABLE workflow_nodes
  ADD CONSTRAINT workflow_nodes_kind_check
  CHECK (kind IN ('agent','merge','approval','action','condition'));

ALTER TABLE workflow_nodes ADD COLUMN IF NOT EXISTS design_note text;
ALTER TABLE workflow_nodes ADD COLUMN IF NOT EXISTS blurb text;
ALTER TABLE workflow_nodes ADD COLUMN IF NOT EXISTS details jsonb DEFAULT '{}'::jsonb;

ALTER TABLE workflows ADD COLUMN IF NOT EXISTS cost_unit text DEFAULT 'run';
ALTER TABLE workflows ADD COLUMN IF NOT EXISTS run_banner jsonb;

-- Données : workflows
UPDATE workflows SET description='De la capture du lead à l''écriture de l''opportunité, avec contrôle de remise et approbation avant engagement.', chain='["Yasmine", "Mehdi", "Karim", "Salma", "Anas", "Nadia", "MERGE", "APPROB.", "CRM"]'::jsonb, node_count='9', merge_count='1', approval_count='1', cost_estimate='33.00', run_label='#2291', cost_unit='run', run_banner='{"text": "Salma — échec appel CRM (timeout). Le retry repart du dernier output validé, jamais du début.", "tone": "alert", "title": "Point de reprise", "actions": ["Reprendre depuis ce nœud", "Agent de repli", "Intervention manuelle", "Arrêter le run"]}'::jsonb, studio_ready='t' WHERE slug='prospect-to-cash';
UPDATE workflows SET description='Du signal marché au plan média chiffré et aux contenus prêts à publier.', chain='["Sofia", "Othmane", "Lina", "Anas", "MERGE", "APPROB.", "PUBLICATION"]'::jsonb, node_count='7', merge_count='1', approval_count='1', cost_estimate='49.00', run_label='#0418', cost_unit='run', run_banner='{"text": "Aucun incident. Le run attend la validation du plan média (400 k MAD) ; la publication démarre dès l''accord.", "tone": "info", "title": "Run en pause", "actions": ["Ouvrir la demande", "Relancer l''approbatrice", "Déléguer"]}'::jsonb, studio_ready='t' WHERE slug='idee-marketing';
UPDATE workflows SET description='Tri du ticket, orientation vers Imane, Zineb ou un humain, puis analyse des causes racines en fin de cycle.', chain='["Imane", "CONDITION", "Zineb", "ESCALADE", "Hamza", "CLÔTURE"]'::jsonb, node_count='8', merge_count='1', approval_count='1', cost_estimate='1.90', run_label='#5530', cost_unit='ticket', run_banner='{"text": "2 tickets attendent une décision humaine. Le reste de la file continue : une escalade ne bloque jamais les autres branches.", "tone": "info", "title": "Escalades ouvertes", "actions": ["Ouvrir l''escalade", "Réassigner", "Répondre manuellement"]}'::jsonb, studio_ready='t' WHERE slug='support-client';

-- Données : nœuds
DELETE FROM workflow_nodes
WHERE workflow_slug IN ('prospect-to-cash', 'idee-marketing', 'support-client');
INSERT INTO workflow_nodes (workflow_slug, node_key, kind, label, agent_slug, version, tag, design_note, blurb, row_index, col_index, parents, mapping, outputs, details, run_state, run_note) VALUES ('idee-marketing','sofia','agent','Sofia · Veille marché','sofia','v1.0',NULL,NULL,'Sofia — détecte le signal marché qui justifie la campagne','0','0','{}','[{"to": "perimetre", "from": "sources.sectorielles"}, {"to": "marches_suivis", "from": "crm.segments"}]'::jsonb,'["veille.signaux[]", "veille.ecarts", "veille.opportunite"]'::jsonb,'{}'::jsonb,'done','3 signaux retenus');
INSERT INTO workflow_nodes (workflow_slug, node_key, kind, label, agent_slug, version, tag, design_note, blurb, row_index, col_index, parents, mapping, outputs, details, run_state, run_note) VALUES ('idee-marketing','othmane','agent','Othmane · Plan de campagne','othmane','v1.5',NULL,NULL,'Othmane — transforme l''opportunité en plan média chiffré','1','0','{sofia}','[{"to": "objectif", "from": "veille.opportunite"}, {"to": "cibles", "from": "crm.segments"}, {"to": "enveloppe", "from": "finance.budget_q4"}]'::jsonb,'["plan.canaux[]", "plan.budget", "plan.calendrier"]'::jsonb,'{}'::jsonb,'done','plan v1 · 400 k MAD');
INSERT INTO workflow_nodes (workflow_slug, node_key, kind, label, agent_slug, version, tag, design_note, blurb, row_index, col_index, parents, mapping, outputs, details, run_state, run_note) VALUES ('idee-marketing','lina','agent','Lina · Contenus','lina',NULL,NULL,NULL,'Lina — produit les formats éditoriaux par canal','2','0','{othmane}','[{"to": "formats", "from": "plan.canaux[]"}, {"to": "ton", "from": "brand.guide"}, {"to": "angle", "from": "veille.signaux[]"}]'::jsonb,'["contenus.posts[]", "contenus.emails[]", "contenus.brief_visuels"]'::jsonb,'{}'::jsonb,'done','14 contenus');
INSERT INTO workflow_nodes (workflow_slug, node_key, kind, label, agent_slug, version, tag, design_note, blurb, row_index, col_index, parents, mapping, outputs, details, run_state, run_note) VALUES ('idee-marketing','anas','agent','Anas · Nurturing','anas',NULL,NULL,NULL,'Anas — séquence email calée sur le calendrier','2','1','{othmane}','[{"to": "cadence", "from": "plan.calendrier"}, {"to": "audience", "from": "crm.segments"}]'::jsonb,'["sequence.touches[]"]'::jsonb,'{}'::jsonb,'done','5 touches');
INSERT INTO workflow_nodes (workflow_slug, node_key, kind, label, agent_slug, version, tag, design_note, blurb, row_index, col_index, parents, mapping, outputs, details, run_state, run_note) VALUES ('idee-marketing','assemble','merge','Assemblage du plan de diffusion',NULL,NULL,'JOIN',NULL,'Aligne contenus et séquence sur le calendrier','3','0','{lina,anas}','[]'::jsonb,'[]'::jsonb,'{"intro": "Les contenus de Lina et la séquence d''Anas sont assemblés en un seul plan de diffusion avant validation.", "blocks": [{"rows": [{"k": "Union des champs", "v": "Tous les champs des branches, collisions signalées."}, {"k": "Priorité par branche", "v": "Le calendrier d''Othmane prime ; contenus et séquence s''y alignent."}, {"k": "Attendre toutes les branches", "v": "Aucune sortie avant complétion de toutes les branches."}], "type": "kv", "label": "Règle de fusion"}, {"rows": [{"k": "Lina · Contenus (CNT-11)", "v": "prioritaire"}, {"k": "Anas · Nurturing (NUR-05)", "v": "complète"}], "type": "pairs", "label": "Branches entrantes"}]}'::jsonb,'done','plan assemblé');
INSERT INTO workflow_nodes (workflow_slug, node_key, kind, label, agent_slug, version, tag, design_note, blurb, row_index, col_index, parents, mapping, outputs, details, run_state, run_note) VALUES ('idee-marketing','validation','approval','Validation direction marketing',NULL,NULL,'SLA 48 H',NULL,'Budget et messages validés avant diffusion','4','0','{assemble}','[]'::jsonb,'[]'::jsonb,'{"link": {"href": "/approvals", "label": "Voir la demande dans la boîte →"}, "intro": "L''approbation est un objet métier : un propriétaire, une échéance, une trace, et un rejet qui relance l''agent avec un motif.", "blocks": [{"rows": [{"v": "Rôle · Direction marketing"}], "type": "kv", "label": "Propriétaire"}, {"rows": [{"v": "48 h, rappel à 24 h"}], "type": "kv", "label": "SLA"}, {"rows": [{"v": "Renvoi à Othmane (CMP-12) avec motif"}], "type": "kv", "label": "Rejet"}, {"rows": [{"v": "Obligatoire au-delà de 100 k MAD"}], "type": "kv", "label": "Seuil"}]}'::jsonb,'waiting','en attente · N. Haddad · 19 h restantes');
INSERT INTO workflow_nodes (workflow_slug, node_key, kind, label, agent_slug, version, tag, design_note, blurb, row_index, col_index, parents, mapping, outputs, details, run_state, run_note) VALUES ('idee-marketing','publish','action','Action · Publication',NULL,NULL,'ACTION',NULL,'Programme posts et campagne email','5','0','{validation}','[{"to": "planner.queue", "from": "contenus.posts[]"}, {"to": "emailing.campaign", "from": "sequence.touches[]"}]'::jsonb,'["publication.ids[]", "campaign.id"]'::jsonb,'{}'::jsonb,'pending','en attente de validation');
INSERT INTO workflow_nodes (workflow_slug, node_key, kind, label, agent_slug, version, tag, design_note, blurb, row_index, col_index, parents, mapping, outputs, details, run_state, run_note) VALUES ('prospect-to-cash','yasmine','agent','Yasmine · Capture','yasmine','v1.4',NULL,NULL,'Yasmine — normalise le signal entrant en fiche prospect','0','0','{}','[{"to": "signal.payload", "from": "webhook.form"}, {"to": "prospect.ref", "from": "crm.account_id"}]'::jsonb,'["prospect.identity", "prospect.source", "prospect.raw_notes"]'::jsonb,'{}'::jsonb,'done',NULL);
INSERT INTO workflow_nodes (workflow_slug, node_key, kind, label, agent_slug, version, tag, design_note, blurb, row_index, col_index, parents, mapping, outputs, details, run_state, run_note) VALUES ('prospect-to-cash','mehdi','agent','Mehdi · Qualification','mehdi','v2.0',NULL,NULL,'Mehdi — note le prospect et produit le cadrage','1','0','{yasmine}','[{"to": "account.name", "from": "prospect.identity"}, {"to": "context.notes", "from": "prospect.raw_notes"}]'::jsonb,'["score.icp", "budget_range", "maturity"]'::jsonb,'{}'::jsonb,'done',NULL);
INSERT INTO workflow_nodes (workflow_slug, node_key, kind, label, agent_slug, version, tag, design_note, blurb, row_index, col_index, parents, mapping, outputs, details, run_state, run_note) VALUES ('prospect-to-cash','karim','agent','Karim · Stratégie','karim','v1.1',NULL,NULL,'Karim — choisit l''angle et la remise admissible','2','0','{mehdi}','[{"to": "fit", "from": "score.icp"}, {"to": "budget", "from": "budget_range"}]'::jsonb,'["approach.angle", "discount.cap", "arguments[]"]'::jsonb,'{}'::jsonb,'done',NULL);
INSERT INTO workflow_nodes (workflow_slug, node_key, kind, label, agent_slug, version, tag, design_note, blurb, row_index, col_index, parents, mapping, outputs, details, run_state, run_note) VALUES ('prospect-to-cash','salma','agent','Salma · Proposition','salma',NULL,NULL,NULL,'Salma — rédige et chiffre la proposition','3','0','{karim}','[{"to": "objectif", "from": "approach.angle"}, {"to": "budget_cadre", "from": "budget_range"}, {"to": "client", "from": "crm.contact"}]'::jsonb,'["proposal.document", "proposal.total_ttc", "proposal.version"]'::jsonb,'{}'::jsonb,'failed','échec — timeout CRM');
INSERT INTO workflow_nodes (workflow_slug, node_key, kind, label, agent_slug, version, tag, design_note, blurb, row_index, col_index, parents, mapping, outputs, details, run_state, run_note) VALUES ('prospect-to-cash','anas','agent','Anas · Nurturing','anas',NULL,NULL,NULL,'Anas — séquence de relance parallèle','3','1','{karim}','[{"to": "theme", "from": "approach.angle"}]'::jsonb,'["sequence.touches[]"]'::jsonb,'{}'::jsonb,'done',NULL);
INSERT INTO workflow_nodes (workflow_slug, node_key, kind, label, agent_slug, version, tag, design_note, blurb, row_index, col_index, parents, mapping, outputs, details, run_state, run_note) VALUES ('prospect-to-cash','nadia','agent','Nadia · Contrôle remise','nadia',NULL,NULL,NULL,'Nadia — vérifie la conformité tarifaire','3','2','{karim}','[{"to": "plafond", "from": "discount.cap"}]'::jsonb,'["verdict", "motif"]'::jsonb,'{}'::jsonb,'done',NULL);
INSERT INTO workflow_nodes (workflow_slug, node_key, kind, label, agent_slug, version, tag, design_note, blurb, row_index, col_index, parents, mapping, outputs, details, run_state, run_note) VALUES ('prospect-to-cash','merge','merge','Fusion des branches',NULL,NULL,'JOIN',NULL,'Combine 3 branches parallèles','4','0','{salma,anas,nadia}','[]'::jsonb,'[]'::jsonb,'{"intro": "Trois branches parallèles convergent. La règle de combinaison est explicite, jamais implicite.", "blocks": [{"rows": [{"k": "Union des champs", "v": "Tous les champs des branches, collisions signalées."}, {"k": "Priorité par branche", "v": "Proposition prime, nurturing complète, remise bloque."}, {"k": "Attendre toutes les branches", "v": "Aucune sortie avant complétion de toutes les branches."}], "type": "kv", "label": "Règle de fusion"}, {"rows": [{"k": "Salma · Proposition (PRP-04)", "v": "prioritaire"}, {"k": "Anas · Nurturing (NUR-05)", "v": "complète"}, {"k": "Nadia · Contrôle remise (REM-06)", "v": "bloquante"}], "type": "pairs", "label": "Branches entrantes"}]}'::jsonb,'waiting','en attente des 3 branches');
INSERT INTO workflow_nodes (workflow_slug, node_key, kind, label, agent_slug, version, tag, design_note, blurb, row_index, col_index, parents, mapping, outputs, details, run_state, run_note) VALUES ('prospect-to-cash','approval','approval','Approbation humaine',NULL,NULL,'SLA 24 H',NULL,'Propriétaire, SLA, motif de rejet','5','0','{merge}','[]'::jsonb,'[]'::jsonb,'{"link": {"href": "/approvals", "label": "Voir la demande dans la boîte →"}, "intro": "L''approbation est un objet métier : un propriétaire, une échéance, une trace, et un rejet qui relance l''agent avec un motif.", "blocks": [{"rows": [{"v": "Rôle · Responsable commercial"}], "type": "kv", "label": "Propriétaire"}, {"rows": [{"v": "24 h, escalade direction au-delà"}], "type": "kv", "label": "SLA"}, {"rows": [{"v": "Renvoi à Salma (PRP-04) avec motif structuré"}], "type": "kv", "label": "Rejet"}, {"rows": [{"v": "Autorisée vers Direction commerciale"}], "type": "kv", "label": "Délégation"}]}'::jsonb,'waiting','en attente · S. Benali · SLA 24 h');
INSERT INTO workflow_nodes (workflow_slug, node_key, kind, label, agent_slug, version, tag, design_note, blurb, row_index, col_index, parents, mapping, outputs, details, run_state, run_note) VALUES ('prospect-to-cash','crm','action','Action CRM',NULL,NULL,'ACTION',NULL,'Écrit l''opportunité et envoie la proposition','6','0','{approval}','[{"to": "crm.attachment", "from": "proposal.document"}, {"to": "crm.amount", "from": "proposal.total_ttc"}]'::jsonb,'["crm.opportunity_id"]'::jsonb,'{}'::jsonb,'pending','en attente');
INSERT INTO workflow_nodes (workflow_slug, node_key, kind, label, agent_slug, version, tag, design_note, blurb, row_index, col_index, parents, mapping, outputs, details, run_state, run_note) VALUES ('support-client','imane_tri','agent','Imane · Tri','imane','v2.4',NULL,NULL,'Imane — classe le ticket, détecte langue et criticité','0','0','{}','[{"to": "ticket", "from": "helpdesk.ticket"}, {"to": "niveau_contrat", "from": "crm.contract_level"}]'::jsonb,'["ticket.categorie", "ticket.criticite", "ticket.langue"]'::jsonb,'{}'::jsonb,'done','14 tickets triés');
INSERT INTO workflow_nodes (workflow_slug, node_key, kind, label, agent_slug, version, tag, design_note, blurb, row_index, col_index, parents, mapping, outputs, details, run_state, run_note) VALUES ('support-client','condition','condition','Condition · Nature du ticket',NULL,NULL,NULL,'3 règles','Oriente chaque ticket vers une seule branche','1','0','{imane_tri}','[]'::jsonb,'[]'::jsonb,'{"note": "Aucune règle ne correspond : le ticket part par défaut en escalade humaine.", "intro": "Les règles sont évaluées dans l''ordre ; la première qui correspond envoie le ticket dans sa branche.", "blocks": [{"rows": [{"k": "Question produit, stock ou commande", "v": "Zineb · Commande"}, {"k": "Question générale, criticité basse", "v": "Imane · Réponse"}, {"k": "Réclamation, ou geste > 500 MAD", "v": "Escalade humaine"}], "type": "rules", "label": "Règles d''orientation"}]}'::jsonb,'done','9 · 3 · 2');
INSERT INTO workflow_nodes (workflow_slug, node_key, kind, label, agent_slug, version, tag, design_note, blurb, row_index, col_index, parents, mapping, outputs, details, run_state, run_note) VALUES ('support-client','imane_reply','agent','Imane · Réponse','imane',NULL,NULL,NULL,'Imane — réponse sourcée depuis la base de connaissance','2','0','{condition}','[{"to": "sujet", "from": "ticket.categorie"}, {"to": "sources", "from": "kb.articles"}]'::jsonb,'["reponse.texte", "reponse.sources[]"]'::jsonb,'{}'::jsonb,'running','9 réponses, 1 en cours');
INSERT INTO workflow_nodes (workflow_slug, node_key, kind, label, agent_slug, version, tag, design_note, blurb, row_index, col_index, parents, mapping, outputs, details, run_state, run_note) VALUES ('support-client','zineb','agent','Zineb · Commande','zineb',NULL,NULL,NULL,'Zineb — répond depuis le catalogue et le suivi de commande','2','1','{condition}','[{"to": "commande", "from": "ticket.order_id"}, {"to": "stock", "from": "catalogue.stock"}]'::jsonb,'["reponse.texte", "commande.statut"]'::jsonb,'{}'::jsonb,'done','3 réponses commande');
INSERT INTO workflow_nodes (workflow_slug, node_key, kind, label, agent_slug, version, tag, design_note, blurb, row_index, col_index, parents, mapping, outputs, details, run_state, run_note) VALUES ('support-client','escalade','approval','Escalade humaine',NULL,NULL,NULL,NULL,'Décision d''un responsable support','2','2','{condition}','[]'::jsonb,'[]'::jsonb,'{"link": {"href": "/approvals", "label": "Voir la demande dans la boîte →"}, "intro": "L''approbation est un objet métier : un propriétaire, une échéance, une trace, et un rejet qui relance l''agent avec un motif.", "blocks": [{"rows": [{"v": "Rôle · Responsable support"}], "type": "kv", "label": "Propriétaire"}, {"rows": [{"v": "4 h ouvrées"}], "type": "kv", "label": "SLA"}, {"rows": [{"v": "Réclamation ou geste > 500 MAD"}], "type": "kv", "label": "Déclencheur"}, {"rows": [{"v": "Retour à Imane avec consigne de réponse"}], "type": "kv", "label": "Rejet"}]}'::jsonb,'waiting','2 en attente · L. Amrani');
INSERT INTO workflow_nodes (workflow_slug, node_key, kind, label, agent_slug, version, tag, design_note, blurb, row_index, col_index, parents, mapping, outputs, details, run_state, run_note) VALUES ('support-client','close','merge','Clôture des branches',NULL,NULL,'JOIN',NULL,'Regroupe les issues de tous les tickets','3','0','{imane_reply,zineb,escalade}','[]'::jsonb,'[]'::jsonb,'{"intro": "Chaque ticket ne suit qu''une branche ; la clôture regroupe les issues pour l''analyse de fin de cycle.", "blocks": [{"rows": [{"k": "Union des champs", "v": "Tous les champs des branches, collisions signalées."}, {"k": "Priorité par branche", "v": "Une escalade ouverte bloque la clôture de son ticket, jamais celle des autres."}, {"k": "Attendre toutes les branches", "v": "Aucune sortie avant complétion de toutes les branches."}], "type": "kv", "label": "Règle de fusion"}, {"rows": [{"k": "Imane · Réponse (SUP-09)", "v": "automatique"}, {"k": "Zineb · Commande (ECO-16)", "v": "automatique"}, {"k": "Escalade humaine", "v": "bloquante pour son ticket"}], "type": "pairs", "label": "Branches entrantes"}]}'::jsonb,'waiting','12 / 14 clos');
INSERT INTO workflow_nodes (workflow_slug, node_key, kind, label, agent_slug, version, tag, design_note, blurb, row_index, col_index, parents, mapping, outputs, details, run_state, run_note) VALUES ('support-client','hamza','agent','Hamza · Causes racines','hamza',NULL,'HEBDO',NULL,'Hamza — agrège les motifs de la semaine','4','0','{close}','[{"to": "corpus", "from": "tickets.clos[]"}]'::jsonb,'["analyse.causes[]", "analyse.recommandations[]"]'::jsonb,'{}'::jsonb,'pending','planifié · vendredi 18:00');
INSERT INTO workflow_nodes (workflow_slug, node_key, kind, label, agent_slug, version, tag, design_note, blurb, row_index, col_index, parents, mapping, outputs, details, run_state, run_note) VALUES ('support-client','action','action','Action · Clôture & rapport',NULL,NULL,'ACTION',NULL,'Clôt les tickets et publie le rapport','5','0','{hamza}','[{"to": "helpdesk.reply", "from": "reponse.texte"}, {"to": "rapport.support", "from": "analyse.causes[]"}]'::jsonb,'["helpdesk.status", "rapport.id"]'::jsonb,'{}'::jsonb,'pending','en attente');