-- 005 · WF-04 « Non-conformité → Amélioration continue » (14 nœuds, boucle « Efficace ? »)
-- Idempotent : peut être rejoué sans erreur. Prérequis : 004 (agents QM) exécuté.

INSERT INTO workflows (slug, name, version, status, code, description, chain, node_count, merge_count, approval_count, cost_estimate, cost_unit, run_label, run_banner, studio_ready, sort_order)
VALUES ('non-conformite', 'Non-conformité → Amélioration continue', 'v1', 'actif', 'WF-04', 'Détection, causes racines, actions corrective et préventive, approbation, mesure d''efficacité et leçon apprise : la boucle PDCA du processus Qualité.', '["Adil", "Ghita", "Rim", "Soufiane", "REVUE", "Meryem", "Bilal", "APPROB.", "Tarik", "Kenza", "EFFICACE ?", "Houda"]'::jsonb, 14, 1, 2, 20.30, 'cycle', 'NC-041', '{"text": "Le plan d''actions (AC-017 corrective, AP-008 préventive) attend l''approbation du manager (SLA 48 h). L''exécution démarre dès l''accord ; si l''efficacité est insuffisante, le cycle repart du PLAN.", "tone": "info", "title": "Cycle NC-041 en cours", "actions": ["Ouvrir la demande", "Voir le cycle PDCA", "Relancer le manager"]}'::jsonb, true, 4)
ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, version=EXCLUDED.version, status=EXCLUDED.status, code=EXCLUDED.code, description=EXCLUDED.description, chain=EXCLUDED.chain, node_count=EXCLUDED.node_count, merge_count=EXCLUDED.merge_count, approval_count=EXCLUDED.approval_count, cost_estimate=EXCLUDED.cost_estimate, cost_unit=EXCLUDED.cost_unit, run_label=EXCLUDED.run_label, run_banner=EXCLUDED.run_banner, studio_ready=EXCLUDED.studio_ready, sort_order=EXCLUDED.sort_order;

DELETE FROM workflow_nodes WHERE workflow_slug = 'non-conformite';

INSERT INTO workflow_nodes (workflow_slug, node_key, kind, label, agent_slug, version, tag, design_note, blurb, row_index, col_index, parents, mapping, outputs, details, run_state, run_note) VALUES
('non-conformite', 'kpi', 'agent', 'Adil · KPI', 'adil', NULL, NULL, NULL, 'Adil — détecte la dérive d''un indicateur', 0, 0, '{}', '[{"from": "erp.commandes", "to": "series"}, {"from": "referentiel.cibles", "to": "cible"}]'::jsonb, '["kpi.valeur", "kpi.derive", "kpi.tendance"]'::jsonb, '{}'::jsonb, 'done', 'dérive 3,8 %'),
('non-conformite', 'ano', 'agent', 'Ghita · Anomalies', 'ghita', NULL, NULL, NULL, 'Ghita — confirme l''anomalie et conserve ses déclencheurs', 1, 0, '{kpi}', '[{"from": "kpi.tendance", "to": "serie"}, {"from": "erp.changements", "to": "evenements"}]'::jsonb, '["anomalie.type", "anomalie.declencheurs[]", "anomalie.perimetre"]'::jsonb, '{}'::jsonb, 'done', 'rupture 2 sept.'),
('non-conformite', 'diag', 'agent', 'Rim · Diagnostic', 'rim', NULL, NULL, NULL, 'Rim — produit le diagnostic initial priorisé', 2, 0, '{ano}', '[{"from": "kpi.derive", "to": "ecart"}, {"from": "anomalie.perimetre", "to": "perimetre"}]'::jsonb, '["diagnostic.ecarts", "diagnostic.risques", "diagnostic.priorite"]'::jsonb, '{}'::jsonb, 'done', 'priorité haute'),
('non-conformite', 'rca', 'agent', 'Soufiane · Causes racines', 'soufiane', NULL, NULL, NULL, 'Soufiane — classe des hypothèses de cause, sans conclure', 3, 0, '{diag}', '[{"from": "diagnostic.ecarts", "to": "probleme"}, {"from": "anomalie.declencheurs[]", "to": "preuves"}, {"from": "kb.causes", "to": "historique"}]'::jsonb, '["rca.hypotheses[]", "rca.preuves[]", "rca.confiance", "rca.investigation"]'::jsonb, '{}'::jsonb, 'done', '3 hypothèses'),
('non-conformite', 'rev', 'approval', 'Revue de la cause · humain', NULL, NULL, 'HUMAIN', NULL, 'Le responsable qualité retient une cause', 4, 0, '{rca}', '[]'::jsonb, '[]'::jsonb, '{"link": {"href": "/approvals", "label": "Voir la demande dans la boîte →"}, "intro": "L''approbation est un objet métier : un propriétaire, une échéance, une trace. Ici, un humain retient une cause parmi les hypothèses classées par Soufiane.", "blocks": [{"rows": [{"v": "Rôle · Responsable qualité"}], "type": "kv", "label": "Propriétaire"}, {"rows": [{"v": "Retenir une cause, ou demander une investigation"}], "type": "kv", "label": "Décision"}, {"rows": [{"v": "Hypothèse IA et cause retenue conservées séparément"}], "type": "kv", "label": "Registre"}]}'::jsonb, 'done', 'cause retenue · A. Kettani'),
('non-conformite', 'cor', 'agent', 'Meryem · Action corrective', 'meryem', NULL, NULL, NULL, 'Meryem — transforme la cause retenue en action', 5, 0, '{rev}', '[{"from": "decision.cause", "to": "cause"}, {"from": "dsi.planning", "to": "ressources"}]'::jsonb, '["action.description", "action.responsable", "action.echeance", "action.verification"]'::jsonb, '{}'::jsonb, 'done', 'AC-017 proposée'),
('non-conformite', 'prev', 'agent', 'Bilal · Préventive', 'bilal', NULL, NULL, NULL, 'Bilal — cherche où la même cause peut frapper', 5, 1, '{rev}', '[{"from": "decision.cause", "to": "cause"}, {"from": "erp.formulaires", "to": "perimetre"}]'::jsonb, '["prevention.risques[]", "prevention.actions[]"]'::jsonb, '{}'::jsonb, 'running', 'AP-008 en préparation'),
('non-conformite', 'merge', 'merge', 'Plan d''actions consolidé', NULL, NULL, 'JOIN', NULL, 'Corrective + préventives en un seul plan', 6, 0, '{cor,prev}', '[]'::jsonb, '[]'::jsonb, '{"intro": "L''action corrective et les actions préventives forment un seul plan soumis au manager.", "blocks": [{"rows": [{"k": "Union des champs", "v": "Toutes les actions des deux branches, collisions signalées."}, {"k": "Priorité par branche", "v": "Le correctif prime ; le préventif peut être reporté sans bloquer."}, {"k": "Attendre toutes les branches", "v": "Aucune sortie avant complétion des deux branches."}], "type": "kv", "label": "Règle de fusion"}, {"rows": [{"k": "Meryem · Action corrective (QM-06)", "v": "prioritaire"}, {"k": "Bilal · Préventive (QM-07)", "v": "complète"}], "type": "pairs", "label": "Branches entrantes"}]}'::jsonb, 'waiting', 'en attente de Bilal'),
('non-conformite', 'appr', 'approval', 'Approbation manager', NULL, NULL, 'SLA 48 H', NULL, 'Approuver, modifier, reporter ou rejeter', 7, 0, '{merge}', '[]'::jsonb, '[]'::jsonb, '{"link": {"href": "/approvals", "label": "Voir la demande dans la boîte →"}, "intro": "L''approbation est un objet métier : un propriétaire, une échéance, une trace, et un rejet qui relance l''agent avec un motif.", "blocks": [{"rows": [{"v": "Rôle · Manager opérations"}], "type": "kv", "label": "Propriétaire"}, {"rows": [{"v": "48 h, rappel à 24 h"}], "type": "kv", "label": "SLA"}, {"rows": [{"v": "Approuver · Modifier · Reporter · Rejeter"}], "type": "kv", "label": "Issues"}, {"rows": [{"v": "Recommandation IA et décision finale conservées séparément"}], "type": "kv", "label": "Registre"}]}'::jsonb, 'waiting', 'en attente · S. Idrissi · SLA 48 h'),
('non-conformite', 'exec', 'action', 'Exécution de l''action', NULL, NULL, 'ACTION', NULL, 'Mise en œuvre par l''équipe responsable', 8, 0, '{appr}', '[{"from": "action.description", "to": "dsi.ticket"}, {"from": "action.echeance", "to": "dsi.due"}]'::jsonb, '["execution.date", "execution.preuve"]'::jsonb, '{}'::jsonb, 'pending', 'en attente'),
('non-conformite', 'mon', 'agent', 'Tarik · Monitoring', 'tarik', NULL, NULL, NULL, 'Tarik — mesure avant / après', 9, 0, '{exec}', '[{"from": "kpi.reference", "to": "baseline"}, {"from": "execution.date", "to": "debut_mesure"}]'::jsonb, '["mesure.actuel", "mesure.amelioration", "mesure.periode"]'::jsonb, '{}'::jsonb, 'pending', 'en attente'),
('non-conformite', 'imp', 'agent', 'Kenza · Amélioration', 'kenza', NULL, NULL, NULL, 'Kenza — évalue l''efficacité, propose la suite', 10, 0, '{mon}', '[{"from": "mesure.amelioration", "to": "effet"}, {"from": "kb.cas_comparables", "to": "historique"}]'::jsonb, '["efficacite.statut", "opportunites[]"]'::jsonb, '{}'::jsonb, 'pending', 'en attente'),
('non-conformite', 'eff', 'condition', 'Efficace ?', NULL, NULL, 'BOUCLE', '3 règles', 'Clôturer ou relancer le cycle', 11, 0, '{imp}', '[]'::jsonb, '[]'::jsonb, '{"intro": "Le résultat de Tarik et Kenza décide de la suite : clôture, ou retour au PLAN avec les données du tour précédent.", "note": "Sans mesure sur 2 périodes, le cas reste ouvert en surveillance.", "blocks": [{"rows": [{"k": "KPI sous la cible pendant 2 périodes", "v": "Clôture + Houda · Leçon apprise"}, {"k": "Amélioration partielle", "v": "↺ Retour à Soufiane · Causes racines"}, {"k": "Aucune amélioration", "v": "↺ Retour à Rim · nouveau diagnostic"}], "type": "rules", "label": "Règles de décision"}], "loops": [{"to": "rca", "label": "Amélioration partielle"}, {"to": "diag", "label": "Aucune amélioration"}]}'::jsonb, 'pending', 'en attente'),
('non-conformite', 'lesson', 'agent', 'Houda · Leçon apprise', 'houda', NULL, NULL, NULL, 'Houda — capitalise pour les cycles suivants', 12, 0, '{eff}', '[{"from": "dossier.nc", "to": "cas"}, {"from": "decisions[]", "to": "decisions"}]'::jsonb, '["lecon.id", "lecon.regle", "lecon.reutilisations[]"]'::jsonb, '{}'::jsonb, 'pending', 'en attente');

-- Vérification attendue : 1 workflow WF-04, 14 nœuds, 9 agents, 2 approbations, 1 condition
SELECT (SELECT COUNT(*) FROM workflows WHERE code='WF-04') AS workflow,
 (SELECT COUNT(*) FROM workflow_nodes WHERE workflow_slug='non-conformite') AS noeuds,
 (SELECT COUNT(*) FROM workflow_nodes WHERE workflow_slug='non-conformite' AND kind='agent') AS agents,
 (SELECT COUNT(*) FROM workflow_nodes WHERE workflow_slug='non-conformite' AND kind='approval') AS approbations,
 (SELECT COUNT(*) FROM workflow_nodes WHERE workflow_slug='non-conformite' AND kind='condition') AS conditions;